import type { Metadata } from "next";
// Removed Google font fetching to avoid build-time network errors on Vercel
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";

// Use system fonts via CSS to keep builds deterministic

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
